####################################################################
#      3.1 Predicting a relation based on Indian Bu???et Process     #
####################################################################
setwd("C:/Users/Vale/Dropbox/Poli/Erasmus/KTH/Statitical Methods for Applied Computer Science/Assignments/Assignment 2/GitHub/task7")
source("task7_functions.R")

# Generate the data
N = 15
X = matrix(2, nrow = N, ncol = N)
alpha = 15

for (i in 1:N){
  
  # Randomly create existing (set to 1) and non-existing links (set to 0)
  # Non observed data are set to 2
  n1 = sample(1:(N-1),1)
  n2 = sample(1:(N-1),1)
  while((n1+n2) >= (N-1)){
    n1 = sample(1:(N-1),1)
    n2 = sample(1:(N-1),1)
  }
  S = setdiff(1:N, i)
  pos = sample(S, n1)
  X[i,pos] = 1
  S = setdiff(S, pos)
  neg = sample(S, n2)
  X[i,neg] = 0
  X[i,i] = 1
  
}

Z = IBP(N, alpha)

K = dim(Z)[2]
W = matrix(0, nrow = K, ncol = K)
sigma = 0.5

for (k1 in 1:K){
  for (k2 in 1:K){
    if (k1!=k2)
      W[k1,k2] = rnorm(1, 0, sigma)
    else
      W[k1,k2] = 10
  }
}

Z1 = Z
W1 = W

num_samples = 1000
for (n in 1:num_samples){
  list1 = update_Z(Z, W, alpha)
  Z = list1[[1]]
  W = list1[[2]]
  
  list2 = update_W(Z,W)
  Z = list2[[1]]
  W = list2[[2]]
}

x11()
image(t(Z), main="Final feature matrix", xlab = "Features / Dishes", ylab = "Customers")

x11()
image(t(Z1), main="Initial feature matrix generated by the IBP", xlab = "Features / Dishes", ylab = "Customers")

